name: Hello,World"
on:
  workflow_dispatch:
    inputs:
      name:
        description: set_names
        required: true
        type: string
        default: そういことね

  push:
    branches:
      - "2024/02/*"

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "test ${{github.event.inputs.name}}"
