name: Hello,World"
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'NAME'
        required: true

  push:
    branches:
      - "2024/02/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        name: Greeting
      - run: echo "test ${{github.event.inputs.name}}"
