name: Hello,World"
on:
  workflow_dispatch:
    inputs:
      name:
        description: テスト
        required: true

  push:
    branches:
      - "2024/02/*"

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "test ${{github.event.inputs.name}}"
